javafx:
    title: Code Generator
    appicons:
          - /image/logo.png
    stage:
#         width: 800 # defaults to the size of the scene
#         height: 600
#         resizable: false # defaults to true
#         style: utility # defaults to DECORATED see: javafx.stage.StageStyle

banner:
  location: banner.txt
  charset: utf-8


